### ISSUE TITLE
Accessing env variables.

### ISSUE THREAD

**Issue by lmeullibre** [brody192/vite-react-template#1]
Hello,
Foremost apologies if this have been asked/covered before on some other thread.
I was wondering how can I access the env variables I set on the Variables window from the Railway dashboard. I have the key `VITE_APP_API_KEY` which is accessed via:    `apiKey: import.meta.env.VITE_APP_API_KEY,` but unfortunately returns undefined. Any suggestion? 
Thank you so much.

**Comment by brody192** [comment]
Hi,
I would be happy to help you, but can you please ask in our discord! (discord.gg/railway)[https://discord.gg/railway]
